import {
  Layout,
  Type,
  Image as ImageIcon,
  AlignLeft,
  PlayCircle,
  Square,
  Star,
  Minus,
  MoveVertical,
  MapPin,
  Sparkles,
  Newspaper,
  Grid,
  Mail,
  Zap,
  TrendingUp,
  Megaphone,
  Film,
  ThumbsUp,
  Package,
  Hash,
  BarChart2,
  List,
  Share2,
  AlertTriangle,
  Code,
  Laptop,
  Layers,
  PhoneCall,
  Clock,
  Briefcase,
  Users,
} from "lucide-react";

export interface ElementorWidgetDefinition {
  id: string;
  name: string;
  category: "basic" | "pro" | "general" | "site";
  icon: any;
  targetSection: string;
  description: string;
  isPro?: boolean;
}

export const ELEMENTOR_WIDGETS: ElementorWidgetDefinition[] = [
  // BASIC
  {
    id: "inner-section",
    name: "Inner Section",
    category: "basic",
    icon: Layout,
    targetSection: "hero",
    description: "Adds nested columns and flexible flexbox containers.",
  },
  {
    id: "heading",
    name: "Heading",
    category: "basic",
    icon: Type,
    targetSection: "hero",
    description: "Add high-contrast headline tags (H1 - H6) with custom typography.",
  },
  {
    id: "image",
    name: "Image",
    category: "basic",
    icon: ImageIcon,
    targetSection: "studio",
    description: "Upload, resize and style media library images with captions.",
  },
  {
    id: "text-editor",
    name: "Text Editor",
    category: "basic",
    icon: AlignLeft,
    targetSection: "about",
    description: "Rich WYSIWYG text paragraphs and editorial copy.",
  },
  {
    id: "video",
    name: "Video / Media",
    category: "basic",
    icon: PlayCircle,
    targetSection: "hero",
    description: "Multi-clip video streamer and looping ambient media.",
  },
  {
    id: "button",
    name: "Button",
    category: "basic",
    icon: Square,
    targetSection: "contact",
    description: "Interactive call-to-action button with hover states and links.",
  },
  {
    id: "star-rating",
    name: "Star Rating",
    category: "basic",
    icon: Star,
    targetSection: "results",
    description: "5-star client ratings and verified Clutch/Google reviews.",
  },
  {
    id: "divider",
    name: "Divider",
    category: "basic",
    icon: Minus,
    targetSection: "highlights",
    description: "Hairline subtle dividers separating content blocks.",
  },
  {
    id: "spacer",
    name: "Spacer",
    category: "basic",
    icon: MoveVertical,
    targetSection: "highlights",
    description: "Adjustable vertical whitespace spacer.",
  },
  {
    id: "google-maps",
    name: "Google Maps",
    category: "basic",
    icon: MapPin,
    targetSection: "contact",
    description: "Interactive studio map pin and office branch address.",
  },
  {
    id: "icon",
    name: "Icon",
    category: "basic",
    icon: Sparkles,
    targetSection: "services",
    description: "Scalable vector Lucide icon with colored badge wrapper.",
  },

  // PRO
  {
    id: "posts",
    name: "Posts & Blog",
    category: "pro",
    icon: Newspaper,
    targetSection: "about",
    isPro: true,
    description: "Rank Math dynamic blog feed with SEO schema.",
  },
  {
    id: "portfolio-grid",
    name: "Portfolio Grid",
    category: "pro",
    icon: Grid,
    targetSection: "services",
    isPro: true,
    description: "Interactive showcase of client projects and web apps.",
  },
  {
    id: "form",
    name: "Form & Inquiries",
    category: "pro",
    icon: Mail,
    targetSection: "contact",
    isPro: true,
    description: "Conversion lead form routed to SQLite CRM & Webhook.",
  },
  {
    id: "animated-headline",
    name: "Animated Headline",
    category: "pro",
    icon: Zap,
    targetSection: "hero",
    isPro: true,
    description: "Rotating kinetic typography and highlight badge accents.",
  },
  {
    id: "price-table",
    name: "Metrics Counter",
    category: "pro",
    icon: TrendingUp,
    targetSection: "results",
    isPro: true,
    description: "ROAS multipliers, shipped sites, and delivery speeds.",
  },
  {
    id: "call-to-action",
    name: "Call to Action",
    category: "pro",
    icon: Megaphone,
    targetSection: "contact",
    isPro: true,
    description: "Full-width booking banner with response time guarantees.",
  },
  {
    id: "media-carousel",
    name: "Media Carousel",
    category: "pro",
    icon: Film,
    targetSection: "hero",
    isPro: true,
    description: "Hero video tabs (Engineering, Design, Speed, Studio).",
  },
  {
    id: "reviews-carousel",
    name: "Reviews Carousel",
    category: "pro",
    icon: ThumbsUp,
    targetSection: "results",
    isPro: true,
    description: "Verified customer testimonials and client endorsements.",
  },

  // GENERAL
  {
    id: "image-box",
    name: "Image Box",
    category: "general",
    icon: Package,
    targetSection: "studio",
    description: "Image paired with heading and descriptive copy.",
  },
  {
    id: "counter",
    name: "Counter",
    category: "general",
    icon: Hash,
    targetSection: "results",
    description: "Animated numeric counter measuring performance metrics.",
  },
  {
    id: "progress-bar",
    name: "Progress Bar",
    category: "general",
    icon: BarChart2,
    targetSection: "highlights",
    description: "Core Web Vitals 100/100 performance visualizer.",
  },
  {
    id: "icon-list",
    name: "Icon List",
    category: "general",
    icon: List,
    targetSection: "services",
    description: "Bullet points with checkmark icons for service deliverables.",
  },
  {
    id: "social-icons",
    name: "Social Channels",
    category: "general",
    icon: Share2,
    targetSection: "contact",
    description: "WhatsApp, Telegram, Viber, and Direct Phone desks.",
  },
  {
    id: "alert",
    name: "Alert Banner",
    category: "general",
    icon: AlertTriangle,
    targetSection: "hero",
    description: "Important studio announcements and availability notices.",
  },
  {
    id: "html",
    name: "Custom HTML",
    category: "general",
    icon: Code,
    targetSection: "footer",
    description: "Raw embed code, custom tracking pixels, or scripts.",
  },

  // SITE CMS
  {
    id: "hero-cms",
    name: "Hero Showcase",
    category: "site",
    icon: Laptop,
    targetSection: "hero",
    description: "Main landing headline, subtitle, and video clips.",
  },
  {
    id: "bento-cms",
    name: "Bento Highlights",
    category: "site",
    icon: Layers,
    targetSection: "highlights",
    description: "Bento grid cards showcasing architectural pillars.",
  },
  {
    id: "services-cms",
    name: "Services Section",
    category: "site",
    icon: Briefcase,
    targetSection: "services",
    description: "Full service offering packages and design deliverables.",
  },
  {
    id: "about-cms",
    name: "About & Process",
    category: "site",
    icon: Users,
    targetSection: "about",
    description: "4-step engineering process and studio gallery.",
  },
  {
    id: "studio-cms",
    name: "Studio & Principles",
    category: "site",
    icon: Sparkles,
    targetSection: "studio",
    description: "Design philosophy, Kyiv loft photo, and city map tag.",
  },
  {
    id: "results-cms",
    name: "Results & Proof",
    category: "site",
    icon: TrendingUp,
    targetSection: "results",
    description: "Conversion multipliers and shipped project proof.",
  },
  {
    id: "contact-cms",
    name: "Contact & Desks",
    category: "site",
    icon: PhoneCall,
    targetSection: "contact",
    description: "Studio addresses, multiple WhatsApps, and inquiry form.",
  },
  {
    id: "footer-cms",
    name: "Footer & Copyright",
    category: "site",
    icon: Clock,
    targetSection: "footer",
    description: "Tagline, copyright year, and legal disclosures.",
  },
];
