import type { FullThemeItem, ThemeLayoutSettings } from "./theme-types";
import { buildThemeFiles } from "./theme-files";
import { DEFAULT_HOME_SEQUENCE } from "@/lib/theme-engine";

const ALL_ON = Object.fromEntries(DEFAULT_HOME_SEQUENCE.map((id) => [id, true]));

function layout(
  hero: ThemeLayoutSettings["heroLayout"],
  extras: Partial<ThemeLayoutSettings> = {},
): ThemeLayoutSettings {
  return {
    heroLayout: hero,
    sectionsOrder: extras.sectionsOrder || [...DEFAULT_HOME_SEQUENCE],
    sectionVisibility: extras.sectionVisibility || { ...ALL_ON },
    cardStyle: extras.cardStyle || "glass",
    fontSizeScale: extras.fontSizeScale || "normal",
  };
}

type ThemeSeed = Omit<FullThemeItem, "files">;

function hydrate(seed: ThemeSeed): FullThemeItem {
  const item: Omit<FullThemeItem, "files"> = {
    ...seed,
    layout: seed.layout || layout(seed.heroLayout || "streamer"),
    phpVersion: seed.phpVersion || "8.1+",
    wpVersion: seed.wpVersion || "6.5+",
    isInstalled: seed.isInstalled !== false,
    isBlockTheme: seed.isBlockTheme !== false,
  };
  return { ...item, files: buildThemeFiles(item) };
}

export const DEFAULT_THEMES: FullThemeItem[] = [
  hydrate({
    id: "codex-pro",
    name: "Codex Dynamics Pro",
    version: "3.2.0",
    author: "Codex Studio",
    authorUrl: "https://codexdynamics.io",
    description:
      "The original studio theme. Floating glass island, video streamer, Apple-grade type — this is the live default and it stays exactly as designed.",
    tags: ["Default", "Apple", "Glass Island", "Video Hero", "Agency"],
    rating: 5,
    reviewsCount: 1840,
    screenshotUrl: "/hero/studio.jpg",
    colors: {
      primary: "#0071e3",
      accent: "#0071e3",
      background: "#f5f5f7",
      cardBg: "#ffffff",
      textMain: "#1d1d1f",
      textMuted: "#6e6e73",
      secondary: "#fbfbfd",
      surface: "#ffffff",
      border: "#d2d2d7",
      inverse: "#1d1d1f",
      highlight: "#0077ed",
      ring: "#0071e3",
    },
    fontFamily: "system",
    headerStyle: "floating",
    containerWidth: "1280px",
    borderRadius: "modern",
    heroLayout: "streamer",
    layout: layout("streamer", { cardStyle: "glass", fontSizeScale: "normal" }),
    activeCount: "Live site",
    category: "installed",
    isDefault: true,
  }),
  hydrate({
    id: "lumen-glass",
    name: "Lumen Glass",
    version: "1.4.0",
    author: "Codex Studio",
    authorUrl: "https://codexdynamics.io",
    description:
      "A brighter iOS product page. Full-width frosted bar, split cinema hero, and airy white planes — like a launch event microsite.",
    tags: ["iOS", "Frosted Bar", "Split Hero", "Product"],
    rating: 5,
    reviewsCount: 612,
    screenshotUrl: "/hero/design.jpg",
    colors: {
      primary: "#0a84ff",
      accent: "#64d2ff",
      background: "#fbfbfd",
      cardBg: "#ffffff",
      textMain: "#1d1d1f",
      textMuted: "#86868b",
      secondary: "#f5f5f7",
      surface: "#ffffff",
      border: "rgba(0,0,0,0.06)",
      inverse: "#000000",
      highlight: "#0a84ff",
      ring: "#0a84ff",
    },
    fontFamily: "system",
    headerStyle: "sticky",
    containerWidth: "1440px",
    borderRadius: "pill",
    heroLayout: "split",
    layout: layout("split", {
      cardStyle: "glass",
      fontSizeScale: "spacious",
      sectionsOrder: ["hero", "highlights", "services", "portfolio", "results", "reviews", "about", "studio", "blog", "contact"],
    }),
    activeCount: "12,400+",
    category: "installed",
  }),
  hydrate({
    id: "studio-noir",
    name: "Studio Noir",
    version: "2.0.1",
    author: "Codex Studio",
    authorUrl: "https://codexdynamics.io",
    description:
      "Cinematic night mode. Opaque top bar, full-bleed streamer, charcoal planes — a premiere house for dark product films.",
    tags: ["Dark", "Cinematic", "Sticky Bar", "Night"],
    rating: 5,
    reviewsCount: 980,
    screenshotUrl: "/hero/studio.jpg",
    colors: {
      primary: "#7eb8ff",
      accent: "#a8d4ff",
      background: "#0c0c0e",
      cardBg: "#161618",
      textMain: "#f5f5f7",
      textMuted: "#a1a1a6",
      secondary: "#111114",
      surface: "#1c1c1e",
      border: "rgba(255,255,255,0.1)",
      inverse: "#f5f5f7",
      highlight: "#7eb8ff",
      ring: "#7eb8ff",
    },
    fontFamily: "inter",
    headerStyle: "sticky",
    containerWidth: "1280px",
    borderRadius: "clean",
    heroLayout: "streamer",
    layout: layout("streamer", {
      cardStyle: "elevated",
      fontSizeScale: "normal",
      sectionsOrder: ["hero", "portfolio", "highlights", "results", "services", "reviews", "studio", "about", "blog", "contact"],
    }),
    activeCount: "8,200+",
    category: "favorites",
  }),
  hydrate({
    id: "editorial-vellum",
    name: "Editorial Vellum",
    version: "1.2.0",
    author: "Atelier Press",
    authorUrl: "https://codexdynamics.io",
    description:
      "A magazine masthead on warm paper. Centered serif identity, editorial hero, generous columns — prestige publishing, not a template.",
    tags: ["Editorial", "Serif", "Masthead", "Paper"],
    rating: 5,
    reviewsCount: 744,
    screenshotUrl: "/studio/design.jpg",
    colors: {
      primary: "#1d1d1f",
      accent: "#3a3c40",
      background: "#f6f1e8",
      cardBg: "#fffaf3",
      textMain: "#2a2420",
      textMuted: "#7a7168",
      secondary: "#efe6d8",
      surface: "#fffaf3",
      border: "rgba(42,36,32,0.12)",
      inverse: "#2a2420",
      highlight: "#8a6a45",
      ring: "#2a2420",
    },
    fontFamily: "playfair",
    headerStyle: "classic",
    containerWidth: "1200px",
    borderRadius: "clean",
    heroLayout: "editorial",
    layout: layout("editorial", {
      cardStyle: "bordered",
      fontSizeScale: "editorial",
      sectionsOrder: ["hero", "highlights", "about", "portfolio", "studio", "services", "reviews", "results", "blog", "contact"],
    }),
    activeCount: "6,100+",
    category: "popular",
  }),
  hydrate({
    id: "nordic-mist",
    name: "Nordic Mist",
    version: "1.1.2",
    author: "North Studio",
    authorUrl: "https://codexdynamics.io",
    description:
      "Quiet Scandinavian product design. Hairline header, centered type, cool stone surfaces — almost nothing, perfectly placed.",
    tags: ["Minimal", "Nordic", "Centered", "Quiet"],
    rating: 4.9,
    reviewsCount: 531,
    screenshotUrl: "/studio/interior.jpg",
    colors: {
      primary: "#1f4e5f",
      accent: "#3f7a86",
      background: "#f3f5f6",
      cardBg: "#ffffff",
      textMain: "#1c2326",
      textMuted: "#5c6b70",
      secondary: "#e8ecee",
      surface: "#ffffff",
      border: "rgba(28,35,38,0.1)",
      inverse: "#1c2326",
      highlight: "#1f4e5f",
      ring: "#1f4e5f",
    },
    fontFamily: "inter",
    headerStyle: "minimal",
    containerWidth: "1200px",
    borderRadius: "modern",
    heroLayout: "centered",
    layout: layout("centered", {
      cardStyle: "bordered",
      fontSizeScale: "spacious",
      sectionsOrder: ["hero", "highlights", "services", "portfolio", "about", "results", "studio", "reviews", "blog", "contact"],
    }),
    activeCount: "9,400+",
    category: "installed",
  }),
  hydrate({
    id: "mono-frame",
    name: "Mono Frame",
    version: "2.1.0",
    author: "Atelier Form",
    authorUrl: "https://codexdynamics.io",
    description:
      "Architectural monochrome. Sharp frames, a two-row masthead, no radius — Swiss poster discipline applied to a studio site.",
    tags: ["Brutalist", "Mono", "Architecture", "Sharp"],
    rating: 5,
    reviewsCount: 1102,
    screenshotUrl: "/work/system.jpg",
    colors: {
      primary: "#111111",
      accent: "#111111",
      background: "#ffffff",
      cardBg: "#f4f4f5",
      textMain: "#111111",
      textMuted: "#52525b",
      secondary: "#fafafa",
      surface: "#ffffff",
      border: "#111111",
      inverse: "#111111",
      highlight: "#111111",
      ring: "#111111",
    },
    fontFamily: "syne",
    headerStyle: "classic",
    containerWidth: "1280px",
    borderRadius: "sharp",
    heroLayout: "centered",
    layout: layout("centered", {
      cardStyle: "bordered",
      fontSizeScale: "spacious",
      sectionsOrder: ["hero", "portfolio", "results", "highlights", "services", "reviews", "studio", "about", "blog", "contact"],
    }),
    activeCount: "4,800+",
    category: "favorites",
  }),
  hydrate({
    id: "pacific-depth",
    name: "Pacific Depth",
    version: "1.3.0",
    author: "Codex Studio",
    authorUrl: "https://codexdynamics.io",
    description:
      "Deep sea glass. A solid navigation bar, split media, teal on ink — the studio as a night ocean, not a dashboard.",
    tags: ["Teal", "Split", "Dark Glass", "Wide"],
    rating: 4.9,
    reviewsCount: 688,
    screenshotUrl: "/hero/web-dev.jpg",
    colors: {
      primary: "#7dd3d0",
      accent: "#9ee8e4",
      background: "#071316",
      cardBg: "#0e1f24",
      textMain: "#e8f6f5",
      textMuted: "#8fb4b1",
      secondary: "#0a181c",
      surface: "#123038",
      border: "rgba(125,211,208,0.16)",
      inverse: "#e8f6f5",
      highlight: "#7dd3d0",
      ring: "#7dd3d0",
    },
    fontFamily: "inter",
    headerStyle: "sticky",
    containerWidth: "1440px",
    borderRadius: "modern",
    heroLayout: "split",
    layout: layout("split", {
      cardStyle: "glass",
      fontSizeScale: "normal",
      sectionsOrder: ["hero", "results", "services", "portfolio", "highlights", "studio", "reviews", "about", "blog", "contact"],
    }),
    activeCount: "5,600+",
    category: "popular",
  }),
  hydrate({
    id: "atelier-warm",
    name: "Atelier Warm",
    version: "1.0.4",
    author: "Kyiv Atelier",
    authorUrl: "https://codexdynamics.io",
    description:
      "Sunlit stone and copper type. Classic masthead, editorial stack, warm clay cards — a physical studio brochure, digitized.",
    tags: ["Warm", "Atelier", "Editorial", "Clay"],
    rating: 4.8,
    reviewsCount: 409,
    screenshotUrl: "/studio/interior.jpg",
    colors: {
      primary: "#9a4d2e",
      accent: "#c4784d",
      background: "#f4ece4",
      cardBg: "#fff8f2",
      textMain: "#3b2a22",
      textMuted: "#8a6f62",
      secondary: "#eadfd4",
      surface: "#fff8f2",
      border: "rgba(59,42,34,0.1)",
      inverse: "#3b2a22",
      highlight: "#9a4d2e",
      ring: "#9a4d2e",
    },
    fontFamily: "playfair",
    headerStyle: "classic",
    containerWidth: "1200px",
    borderRadius: "clean",
    heroLayout: "editorial",
    layout: layout("editorial", {
      cardStyle: "elevated",
      fontSizeScale: "editorial",
      sectionsOrder: ["hero", "studio", "highlights", "portfolio", "about", "services", "reviews", "results", "blog", "contact"],
    }),
    activeCount: "3,900+",
    category: "popular",
  }),
  hydrate({
    id: "quartz-line",
    name: "Quartz Line",
    version: "1.0.0",
    author: "Codex Studio",
    authorUrl: "https://codexdynamics.io",
    description:
      "Ultra-thin hairline chrome. A single top rule, centered statement, and gallery-white planes — the site as a quiet object.",
    tags: ["Hairline", "Gallery", "Centered", "Quiet"],
    rating: 4.9,
    reviewsCount: 355,
    screenshotUrl: "/studio/wireframes.jpg",
    colors: {
      primary: "#3a3a3c",
      accent: "#636366",
      background: "#ffffff",
      cardBg: "#f7f7f8",
      textMain: "#1c1c1e",
      textMuted: "#8e8e93",
      secondary: "#f2f2f7",
      surface: "#ffffff",
      border: "rgba(60,60,67,0.12)",
      inverse: "#1c1c1e",
      highlight: "#3a3a3c",
      ring: "#3a3a3c",
    },
    fontFamily: "system",
    headerStyle: "minimal",
    containerWidth: "1200px",
    borderRadius: "clean",
    heroLayout: "centered",
    layout: layout("centered", {
      cardStyle: "flat",
      fontSizeScale: "spacious",
      sectionsOrder: ["hero", "services", "highlights", "portfolio", "results", "about", "studio", "reviews", "blog", "contact"],
    }),
    activeCount: "2,700+",
    category: "installed",
  }),
  hydrate({
    id: "horizon-wide",
    name: "Horizon Wide",
    version: "1.5.0",
    author: "Codex Studio",
    authorUrl: "https://codexdynamics.io",
    description:
      "Cinematic landscape. Sticky bar, split theater, 1440px stage — built for work that wants room to breathe.",
    tags: ["Wide", "Cinematic", "Split", "Sticky"],
    rating: 4.9,
    reviewsCount: 720,
    screenshotUrl: "/hero/social.jpg",
    colors: {
      primary: "#155eef",
      accent: "#528bff",
      background: "#f4f6fa",
      cardBg: "#ffffff",
      textMain: "#101828",
      textMuted: "#667085",
      secondary: "#eef2f6",
      surface: "#ffffff",
      border: "rgba(16,24,40,0.08)",
      inverse: "#101828",
      highlight: "#155eef",
      ring: "#155eef",
    },
    fontFamily: "inter",
    headerStyle: "sticky",
    containerWidth: "1440px",
    borderRadius: "modern",
    heroLayout: "split",
    layout: layout("split", {
      cardStyle: "elevated",
      fontSizeScale: "normal",
      sectionsOrder: ["hero", "portfolio", "results", "services", "highlights", "reviews", "studio", "about", "blog", "contact"],
    }),
    activeCount: "7,300+",
    category: "popular",
  }),
  hydrate({
    id: "ink-theater",
    name: "Ink Theater",
    version: "1.1.0",
    author: "Codex Studio",
    authorUrl: "https://codexdynamics.io",
    description:
      "OLED black with the floating island retained. Streamer hero on ink, glass cards that read as stage lighting — night mode of the original.",
    tags: ["OLED", "Island", "Streamer", "Night"],
    rating: 5,
    reviewsCount: 866,
    screenshotUrl: "/hero/studio.jpg",
    colors: {
      primary: "#0a84ff",
      accent: "#64d2ff",
      background: "#000000",
      cardBg: "#1c1c1e",
      textMain: "#f5f5f7",
      textMuted: "#8e8e93",
      secondary: "#111113",
      surface: "#2c2c2e",
      border: "rgba(255,255,255,0.12)",
      inverse: "#f5f5f7",
      highlight: "#0a84ff",
      ring: "#0a84ff",
    },
    fontFamily: "system",
    headerStyle: "floating",
    containerWidth: "1280px",
    borderRadius: "modern",
    heroLayout: "streamer",
    layout: layout("streamer", {
      cardStyle: "glass",
      fontSizeScale: "normal",
    }),
    activeCount: "11,000+",
    category: "favorites",
  }),
  hydrate({
    id: "paper-studio",
    name: "Paper Studio",
    version: "1.0.2",
    author: "Codex Studio",
    authorUrl: "https://codexdynamics.io",
    description:
      "Gallery white with a bento hero. The island stays; the first screen becomes a modular board of clips, metrics, and type.",
    tags: ["Bento", "Gallery", "Island", "Modular"],
    rating: 4.8,
    reviewsCount: 501,
    screenshotUrl: "/studio/design.jpg",
    colors: {
      primary: "#0071e3",
      accent: "#34c759",
      background: "#fafafa",
      cardBg: "#ffffff",
      textMain: "#1d1d1f",
      textMuted: "#6e6e73",
      secondary: "#f2f2f7",
      surface: "#ffffff",
      border: "rgba(0,0,0,0.06)",
      inverse: "#1d1d1f",
      highlight: "#0071e3",
      ring: "#0071e3",
    },
    fontFamily: "system",
    headerStyle: "floating",
    containerWidth: "1280px",
    borderRadius: "modern",
    heroLayout: "bento",
    layout: layout("bento", {
      cardStyle: "elevated",
      fontSizeScale: "normal",
      sectionsOrder: ["hero", "portfolio", "highlights", "services", "results", "studio", "reviews", "about", "blog", "contact"],
    }),
    activeCount: "4,200+",
    category: "installed",
  }),
  hydrate({
    id: "copper-atelier",
    name: "Copper Atelier",
    version: "1.0.1",
    author: "Atelier Press",
    authorUrl: "https://codexdynamics.io",
    description:
      "Burnished copper on cream. Masthead serif, editorial hero, bordered plates — a print house that happens to be a website.",
    tags: ["Copper", "Serif", "Print", "Masthead"],
    rating: 4.8,
    reviewsCount: 298,
    screenshotUrl: "/work/storefront.jpg",
    colors: {
      primary: "#8a4b2f",
      accent: "#b56a42",
      background: "#f7f1ea",
      cardBg: "#fffdf9",
      textMain: "#2c211c",
      textMuted: "#7d6558",
      secondary: "#efe4d8",
      surface: "#fffdf9",
      border: "rgba(138,75,47,0.18)",
      inverse: "#2c211c",
      highlight: "#8a4b2f",
      ring: "#8a4b2f",
    },
    fontFamily: "playfair",
    headerStyle: "classic",
    containerWidth: "1200px",
    borderRadius: "clean",
    heroLayout: "editorial",
    layout: layout("editorial", {
      cardStyle: "bordered",
      fontSizeScale: "editorial",
      sectionsOrder: ["hero", "about", "portfolio", "highlights", "studio", "services", "reviews", "results", "blog", "contact"],
    }),
    activeCount: "2,100+",
    category: "popular",
  }),
  hydrate({
    id: "kyiv-night",
    name: "Kyiv Night",
    version: "1.2.0",
    author: "Codex Studio",
    authorUrl: "https://codexdynamics.io",
    description:
      "Navy glass over the Dnipro after dark. Floating island, split hero, apple-blue signals — the city the studio actually lives in.",
    tags: ["Navy", "Island", "Split", "Kyiv"],
    rating: 5,
    reviewsCount: 640,
    screenshotUrl: "/studio/interior.jpg",
    colors: {
      primary: "#4ea3ff",
      accent: "#7ec0ff",
      background: "#07111c",
      cardBg: "#0d1b2a",
      textMain: "#eaf2fb",
      textMuted: "#8aa0b8",
      secondary: "#0a1622",
      surface: "#122436",
      border: "rgba(78,163,255,0.16)",
      inverse: "#eaf2fb",
      highlight: "#4ea3ff",
      ring: "#4ea3ff",
    },
    fontFamily: "system",
    headerStyle: "floating",
    containerWidth: "1280px",
    borderRadius: "modern",
    heroLayout: "split",
    layout: layout("split", {
      cardStyle: "glass",
      fontSizeScale: "normal",
      sectionsOrder: ["hero", "highlights", "portfolio", "studio", "results", "services", "reviews", "about", "blog", "contact"],
    }),
    activeCount: "5,050+",
    category: "favorites",
  }),
  hydrate({
    id: "soft-lumen",
    name: "Soft Lumen",
    version: "1.0.3",
    author: "Codex Studio",
    authorUrl: "https://codexdynamics.io",
    description:
      "iOS Settings energy. Hairline header, bento first screen, spacious type — calm, large, and extremely considered.",
    tags: ["iOS", "Bento", "Spacious", "Hairline"],
    rating: 4.9,
    reviewsCount: 477,
    screenshotUrl: "/hero/design.jpg",
    colors: {
      primary: "#007aff",
      accent: "#5ac8fa",
      background: "#f2f2f7",
      cardBg: "#ffffff",
      textMain: "#000000",
      textMuted: "#6c6c70",
      secondary: "#e5e5ea",
      surface: "#ffffff",
      border: "rgba(60,60,67,0.12)",
      inverse: "#000000",
      highlight: "#007aff",
      ring: "#007aff",
    },
    fontFamily: "system",
    headerStyle: "minimal",
    containerWidth: "1280px",
    borderRadius: "modern",
    heroLayout: "bento",
    layout: layout("bento", {
      cardStyle: "elevated",
      fontSizeScale: "spacious",
      sectionsOrder: ["hero", "highlights", "services", "results", "portfolio", "studio", "reviews", "about", "blog", "contact"],
    }),
    activeCount: "6,800+",
    category: "installed",
  }),
  hydrate({
    id: "grid-atelier",
    name: "Grid Atelier",
    version: "1.1.1",
    author: "Codex Studio",
    authorUrl: "https://codexdynamics.io",
    description:
      "A modular board from the first pixel. Sticky bar, bento hero, tight geometry — work arranged like a wall in the studio.",
    tags: ["Bento", "Grid", "Sticky", "Modular"],
    rating: 4.8,
    reviewsCount: 390,
    screenshotUrl: "/studio/wireframes.jpg",
    colors: {
      primary: "#1d4ed8",
      accent: "#3b82f6",
      background: "#f8fafc",
      cardBg: "#ffffff",
      textMain: "#0f172a",
      textMuted: "#64748b",
      secondary: "#f1f5f9",
      surface: "#ffffff",
      border: "rgba(15,23,42,0.08)",
      inverse: "#0f172a",
      highlight: "#1d4ed8",
      ring: "#1d4ed8",
    },
    fontFamily: "inter",
    headerStyle: "sticky",
    containerWidth: "1440px",
    borderRadius: "clean",
    heroLayout: "bento",
    layout: layout("bento", {
      cardStyle: "elevated",
      fontSizeScale: "compact",
      sectionsOrder: ["hero", "portfolio", "results", "services", "highlights", "reviews", "studio", "about", "blog", "contact"],
    }),
    activeCount: "3,400+",
    category: "popular",
  }),
];
